php:
  entrypoint: "php-fpm"
  command: ""
  environment:
    SYMFONY_ENV: dev

nginx:
  image: "${APP_NAME}:${APP_VERSION}-nginx"
  ports:
    - "8000:80"
  links:
    - php
  volumes_from:
    - data
  environment:
    PROJECT_NAME: ${PROJECT_NAME}
    PROJECT_WEB_DIR: ${PROJECT_WEB_DIR}
    PROJECT_INDEX_FILE: ${PROJECT_INDEX_FILE}
    PROJECT_DEV_INDEX_FILE: ${PROJECT_DEV_INDEX_FILE}

mongo:
  volumes:
    - ./data:/data/db
  ports:
    - "8111:27017"

mongoclient:
  image: mongoclient/mongoclient
  links:
    - mongo
  ports:
    - "8222:3000"

swagger:
  image: swaggerapi/swagger-editor
  ports:
    - "8333:8080"

rabbit:
  ports:
    - "8444:15672"
  environment:
    RABBITMQ_DEFAULT_USER: user
    RABBITMQ_DEFAULT_PASS: password