php:
  entrypoint: "php-fpm"
  command: ""
  environment:
    SYMFONY_ENV: dev

mongo:
  volumes:
    - ./data:/data/db
  ports:
    - "8003:27017"

nginx:
  image: "${APP_NAME}:${APP_VERSION}-nginx"
  ports:
    - "8000:80"
  links:
    - php
  volumes_from:
    - data
  environment:
    PROJECT_NAME: ${PROJECT_NAME}
    PROJECT_WEB_DIR: ${PROJECT_WEB_DIR}
    PROJECT_INDEX_FILE: ${PROJECT_INDEX_FILE}
    PROJECT_DEV_INDEX_FILE: ${PROJECT_DEV_INDEX_FILE}

mongoclient:
  image: mongoclient/mongoclient
  links:
    - mongo
  ports:
    - "8001:3000"

swagger:
  image: swaggerapi/swagger-editor
  ports:
    - "8002:8080"
