php:
  entrypoint: "php-fpm"
  command: ""
  environment:
    SYMFONY_ENV: dev
  links:
    - phpmyadmin

nginx:
  image: "${APP_NAME}:${APP_VERSION}-nginx"
  ports:
    - "8000:80"
  links:
    - php
  volumes_from:
    - data
  environment:
    PROJECT_NAME: ${PROJECT_NAME}
    PROJECT_WEB_DIR: ${PROJECT_WEB_DIR}
    PROJECT_INDEX_FILE: ${PROJECT_INDEX_FILE}
    PROJECT_DEV_INDEX_FILE: ${PROJECT_DEV_INDEX_FILE}

mysql:
  environment:
    MYSQL_DATABASE: ${PROJECT_NAME}
  volumes:
    - data:/var/lib/mysql
  ports:
    - "8111:3306"

phpmyadmin:
  image: phpmyadmin/phpmyadmin
  links:
    - mysql
  environment:
    PMA_HOST: mysql
    PMA_USER: root
    PMA_PASSWORD: ${PROJECT_NAME}
  ports:
    - "8222:80"


swagger:
  image: swaggerapi/swagger-editor
  ports:
    - "8333:8080"

beanstalkd:
  ports:
    - "8444:11300"