data:
  image: busybox
  volumes:
    - .:/var/www

php:
  image: "${IMAGE_VERSION}"
  entrypoint: "/bin/bash"
  command: "/entrypoint.sh"
  links:
    - mongo
  volumes_from:
    - data
  environment:
    SYMFONY_ENV: test

mongo:
  image: mongo:3.3
