# Learn more about services, parameters and containers at
# http://symfony.com/doc/current/book/service_container.html
parameters:
#    parameter_name: value

services:

  app.model_describer.employee:
    class: AppBundle\StashOdm\EmployeeDescriber
    tags:
      - { name: stash_odm.model }

  app.model_describer.skill:
    class: AppBundle\StashOdm\SkillDescriber
    tags:
      - { name: stash_odm.model }

  app.model_describer.employee.project:
    class: AppBundle\StashOdm\Employee\ProjectDescriber
    tags:
      - { name: stash_odm.model }

  app.model_describer.employee.skill:
    class: AppBundle\StashOdm\Employee\SkillDescriber
    tags:
      - { name: stash_odm.model }
